# Generated by Django 5.1.2 on 2025-01-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=30),
        ),
    ]
