# Generated by Django 5.1 on 2024-11-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Staff', max_length=30),
        ),
    ]
