# Generated by Django 5.1.2 on 2024-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Employee', 'Employee')], default='Staff', max_length=30),
        ),
    ]
