# Generated by Django 5.1.2 on 2024-11-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Employee', 'Employee'), ('Admin', 'Admin')], default='Staff', max_length=30),
        ),
    ]
