# Generated by Django 5.1.2 on 2024-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Admin', 'Admin'), ('Employee', 'Employee')], default='Staff', max_length=30),
        ),
    ]
