# Generated by Django 5.1.2 on 2024-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Staff', max_length=30),
        ),
    ]
