# Generated by Django 5.1.2 on 2024-11-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selles',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
