# Generated by Django 5.1.2 on 2024-11-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_customer_supplier_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='DueAmount',
            new_name='dueAmount',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='PaidAmount',
            new_name='paidAmount',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='SupplierName',
            new_name='suppliername',
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
