# Generated by Django 5.1.2 on 2024-11-09 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_discount_purchase_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('discountAmount', models.IntegerField()),
                ('paidAmount', models.IntegerField()),
                ('DueAmount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerC', to='product.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductP', to='product.product')),
            ],
        ),
    ]
