# Generated by Django 5.1.2 on 2024-12-01 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_purchaseinvoice_grandtotal_purchaseinvoice_dueamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='product.purchaseinvoice'),
            preserve_default=False,
        ),
    ]
