# Generated by Django 5.1.2 on 2024-12-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_purchaseitem_purchase_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase_invoice',
        ),
    ]
