# Generated by Django 5.1.2 on 2025-04-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_type',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('PCS', 'Pieces')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
