# Generated by Django 5.1.2 on 2024-11-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_discountamount_purchaseitem_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='discount',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='suppliername',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='dueAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paidAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
