# Generated by Django 5.1.2 on 2025-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_purchaseitem_quantity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('PCS', 'Pieces')], max_length=10),
        ),
    ]
