# Generated by Django 5.1.2 on 2024-12-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_purchaseinvoice_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='GrandTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='dueAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
