# Generated by Django 5.1.2 on 2024-11-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selles',
            name='created_at',
        ),
        migrations.AddField(
            model_name='selles',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='selles',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
