# Generated by Django 5.1.2 on 2025-05-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellesitem',
            name='quantity_type',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('PCS', 'Pieces')], default='KG', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity_type',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('PCS', 'Pieces')], default='KG', max_length=10),
        ),
    ]
