# Generated by Django 5.1.2 on 2025-05-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_sellesitem_quantity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damaged_quantity', models.IntegerField(default=0)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_stock', to='product.stock')),
            ],
        ),
    ]
