# Generated by Django 5.1.2 on 2024-12-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_totalprice_selles_totalamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selles',
            old_name='totalAmount',
            new_name='totalPrice',
        ),
    ]
