# Generated by Django 5.1.2 on 2024-12-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_selles_dueamount_alter_selles_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='totalAmount',
            new_name='alltotalAmount',
        ),
    ]
