# Generated by Django 5.1.2 on 2025-05-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_damagedproduct_delete_damagedstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damagedproduct',
            old_name='damage_reason',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='damagedproduct',
            old_name='original_purchase_price',
            new_name='purchase_price',
        ),
    ]
