# Generated by Django 5.1.2 on 2024-12-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_totalamount_purchase_alltotalamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='totalAmount',
            new_name='product_totalAmount',
        ),
    ]
