name: Test and Deploy Django to EC2

on:
  push:
    branches:
      - master  # Trigger the workflow when testing branch is updated

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.6
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        source env/bin/activate
        python manage.py test

  deploy:
    name: Deploy Branch
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: master

    - name: Merge testing branch into deployment
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git fetch origin
        git checkout deployment
        git pull origin deployment
        git merge testing --no-ff
        git push origin deployment