name: Test and Deploy Django to EC2

on:
  push:
    branches:
      - master  # Trigger when master branch is updated
  workflow_dispatch:  # 👈 This enables manual trigger from GitHub UI

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source env/bin/activate
          python manage.py test

  deploy:
    name: Merge to Deployment Branch
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Authenticate with GITHUB_TOKEN
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Merge master into deployment
        run: |
          git fetch origin
          git checkout deployment
          git pull origin deployment
          git merge master --no-ff
          git push origin deployment

  deploy-to-ec2:
    name: Deploy to EC2 Server
    runs-on: ubuntu-latest
    needs: deploy
    if: success()

    steps:
      - name: Deploy to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Inventory
            git pull origin deployment
            source env/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            sudo systemctl restart nginx
